version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: RequirementsDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SA
    ports:
      - "5432:5432"
      
  migration:
    build:
      context: .
      dockerfile: MigrationDockerfile
    depends_on:
      - postgres
    environment:
      ConnectionStrings__RequirementsPostgresDatabase: "Host=postgres;Port=5432;Database=RequirementsDatabase;Username=postgres;Password=SA"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      ConnectionStrings__RequirementsPostgresDatabase: "Host=postgres;Port=5432;Database=RequirementsDatabase;Username=postgres;Password=SA"
    ports:
      - "5000:5000"
      - "5001:5001"

  # blazor:
  #     build:
  #       context: .
  #       dockerfile: BlazorDockerfile
  #     ports:
  #       - "5216:5216"
  #     depends_on:
  #       - app